namespace Discord.CSharp.APITypes.Rest
{
    /// <summary>
    /// https://discord.com/developers/docs/topics/opcodes-and-status-codes#json
    /// </summary>
    public enum RESTJSONErrorCodes
    {
        	GeneralError,
            UnknownAccount = 10001,
            UnknownApplication,
            UnknownChannel,
            UnknownGuild,
            UnknownIntegration,
            UnknownInvite,
            UnknownMember,
            UnknownMessage,
            UnknownPermissionOverwrite,
            UnknownProvider,
            UnknownRole,
            UnknownToken,
            UnknownUser,
            UnknownEmoji,
            UnknownWebhook,
            UnknownWebhookService,
            UnknownSession = 10020,
            UnknownAsset,
            UnknownBan = 10026,
            UnknownSKU,
            UnknownStoreListing,
            UnknownEntitlement,
            UnknownBuild,
            UnknownLobby,
            UnknownBranch,
            UnknownStoreDirectoryLayout,
            UnknownRedistributable = 10036,
            UnknownGiftCode = 10038,
            UnknownStream = 10049,
            UnknownPremiumServerSubscribeCooldown,
            UnknownGuildTemplate = 10057,
            UnknownDiscoverableServerCategory = 10059,
            UnknownSticker,
            UnknownStickerPack,
            UnknownInteraction,
            UnknownApplicationCommand,
            UnknownVoiceState = 10065,
            UnknownApplicationCommandPermissions,
            UnknownStageInstance,
            UnknownGuildMemberVerificationForm,
            UnknownGuildWelcomeScreen,
            UnknownGuildScheduledEvent,
            UnknownGuildScheduledEventUser,
            UnknownTag = 10087,
            UnknownSound = 10097,
            BotsCannotUseThisEndpoint = 20001,
            OnlyBotsCanUseThisEndpoint,
            ExplicitContentCannotBeSentToTheDesiredRecipient = 20009,
            NotAuthorizedToPerformThisActionOnThisApplication = 20012,
            ActionCannotBePerformedDueToSlowmodeRateLimit = 20016,
            TheMazeIsntMeantForYou,
            OnlyTheOwnerOfThisAccountCanPerformThisAction,
            AnnouncementEditLimitExceeded = 20022,
            UnderMinimumAge = 20024,
            ChannelSendRateLimit = 20028,
            ServerSendRateLimit,
            StageTopicServerNameServerDescriptionOrChannelNamesContainDisallowedWords = 20031,
            GuildPremiumSubscriptionLevelTooLow = 20035,
            MaximumNumberOfGuildsReached = 30001,
            MaximumNumberOfFriendsReached,
            MaximumNumberOfPinsReachedForTheChannel,
            MaximumNumberOfRecipientsReached,
            MaximumNumberOfGuildRolesReached,
            MaximumNumberOfWebhooksReached = 30007,
            MaximumNumberOfEmojisReached,
            MaximumNumberOfReactionsReached = 30010,
            MaximumNumberOfGroupDMsReached,
            MaximumNumberOfGuildChannelsReached = 30013,
            MaximumNumberOfAttachmentsInAMessageReached = 30015,
            MaximumNumberOfInvitesReached,
            MaximumNumberOfAnimatedEmojisReached = 30018,
            MaximumNumberOfServerMembersReached,
            MaximumNumberOfServerCategoriesReached = 30030,
            GuildAlreadyHasTemplate = 30031,
            MaximumNumberOfApplicationCommandsReached,
            MaximumThreadParticipantsReached,
            MaximumDailyApplicationCommandCreatesReached,
            MaximumNumberOfNonGuildMemberBansHasBeenExceeded,
            MaximumNumberOfBanFetchesHasBeenReached = 30037,
            MaximumNumberOfUncompletedGuildScheduledEventsReached,
            MaximumNumberOfStickersReached = 30039,
            MaximumNumberOfPruneRequestsHasBeenReached,
            MaximumNumberOfGuildWidgetSettingsUpdatesHasBeenReached = 30042,
            MaximumNumberOfSoundboardSoundsReached = 30045,
            MaximumNumberOfEditsToMessagesOlderThanOneHourReached,
            MaximumNumberOfPinnedThreadsInForumHasBeenReached,
            MaximumNumberOfTagsInForumHasBeenReached,
            BitrateIsTooHighForChannelOfThisType = 30052,
            MaximumNumberOfPremiumEmojisReached = 30056,
            MaximumNumberOfWebhooksPerGuildReached = 30058,
            MaximumNumberOfChannelPermissionOverwritesReached = 30060,
            TheChannelsForThisGuildAreTooLarge,
            Unauthorized = 40001,
            VerifyYourAccount,
            OpeningDirectMessagesTooFast,
            SendMessagesHasBeenTemporarilyDisabled,
            RequestEntityTooLarge,
            FeatureTemporarilyDisabledServerSide,
            UserBannedFromThisGuild,
            ConnectionHasBeenRevoked = 40012,
            OnlyConsumableSKUsCanBeConsumed = 40018,
            YouCanOnlyDeleteSandboxEntitlements,
            TargetUserIsNotConnectedToVoice = 40032,
            ThisMessageWasAlreadyCrossposted,
            ApplicationCommandWithThatNameAlreadyExists = 40041,
            ApplicationInteractionFailedToSend = 40043,
            CannotSendAMessageInAForumChannel = 40058,
            InteractionHasAlreadyBeenAcknowledged = 40060,
            TagNamesMustBeUnique,
            ServiceResourceIsBeingRateLimited,
            ThereAreNoTagsAvailableThatCanBeSetByNonModerators = 40066,
            TagRequiredToCreateAForumPostInThisChannel,
            AnEntitlementHasAlreadyBeenGrantedForThisResource = 40074,
            ThisInteractionHasHitTheMaximumNumberOfFollowUpMessages = 40094,
            CloudflareIsBlockingYourRequest = 40333,
            MissingAccess = 50001,
            InvalidAccountType,
            CannotExecuteActionOnDMChannel,
            GuildWidgetDisabled,
            CannotEditMessageAuthoredByAnotherUser,
            CannotSendAnEmptyMessage,
            CannotSendMessagesToThisUser,
            CannotSendMessagesInNonTextChannel,
            ChannelVerificationLevelTooHighForYouToGainAccess,
            OAuth2ApplicationDoesNotHaveBot,
            OAuth2ApplicationLimitReached,
            InvalidOAuth2State,
            MissingPermissions,
            InvalidToken,
            NoteWasTooLong,
            ProvidedTooFewOrTooManyMessagesToDelete,
            InvalidMFALevel,
            MessageCanOnlyBePinnedInTheChannelItWasSentIn = 50019,
            InviteCodeInvalidOrTaken,
            CannotExecuteActionOnSystemMessage,
            CannotExecuteActionOnThisChannelType = 50024,
            InvalidOAuth2AccessToken,
            MissingRequiredOAuth2Scope,
            InvalidWebhookToken = 50027,
            InvalidRole,
            InvalidRecipients = 50033,
            OneOfTheMessagesProvidedWasTooOldForBulkDelete,
            InvalidFormBodyOrContentType,
            InviteAcceptedToGuildWithoutTheBotBeingIn,
            InvalidActivityAction = 50039,
            InvalidAPIVersion = 50041,
            FileUploadedExceedsMaximumSize = 50045,
            InvalidFileUploaded,
            CannotSelfRedeemThisGift = 50054,
            InvalidGuild,
            InvalidSKU = 50057,
            InvalidRequestOrigin = 50067,
            InvalidMessageType,
            PaymentSourceRequiredToRedeemGift = 50070,
            CannotModifyASystemWebhook = 50073,
            CannotDeleteChannelRequiredForCommunityGuilds,
            CannotEditStickersWithinMessage = 50080,
            InvalidStickerSent,
            InvalidActionOnArchivedThread = 50083,
            InvalidThreadNotificationSettings,
            ParameterEarlierThanCreation,
            CommunityServerChannelsMustBeTextChannels,
            TheEntityTypeOfTheEventIsDifferentFromTheEntityYouAreTryingToStartTheEventFor = 50091,
            ServerNotAvailableInYourLocation = 50095,
            ServerNeedsMonetizationEnabledToPerformThisAction = 50097,
            ServerNeedsMoreBoostsToPerformThisAction = 50101,
            RequestBodyContainsInvalidJSON = 50109,
            ProvidedFileIsInvalid,
            ProvidedFileTypeIsInvalid = 50123,
            ProvidedFileDurationExceedsMaximumLength,
            OwnerCannotBePendingMember = 50131,
            OwnershipCannotBeMovedToABotUser,
            FailedToResizeAssetBelowTheMinimumSize = 50138,
            CannotMixSubscriptionAndNonSubscriptionRolesForAnEmoji = 50144,
            CannotConvertBetweenPremiumEmojiAndNormalEmoji,
            UploadedFileNotFound,
            SpecifiedEmojiIsInvalid = 50151,
            VoiceMessagesDoNotSupportAdditionalContent = 50159,
            VoiceMessagesMustHaveASingleAudioAttachment,
            VoiceMessagesMustHaveSupportingMetadata,
            VoiceMessagesCannotBeEdited,
            CannotDeleteGuildSubscriptionIntegration,
            YouCannotSendVoiceMessagesInThisChannel = 50173,
            TheUserAccountMustFirstBeVerified = 50178,
            ProvidedFileDoesNotHaveAValidDuration = 50192,
            YouDoNotHavePermissionToSendThisSticker = 50600,
            TwoFactorAuthenticationIsRequired = 60003,
            NoUsersWithDiscordTagExist = 80004,
            ReactionWasBlocked = 90001,
            UserCannotUseBurstReactions,
            ApplicationNotYetAvailable = 110001,
            APIResourceOverloaded = 130000,
            TheStageIsAlreadyOpen = 150006,
            CannotReplyWithoutPermissionToReadMessageHistory = 160002,
            ThreadAlreadyCreatedForMessage = 160004,
            ThreadLocked,
            MaximumActiveThreads,
            MaximumActiveAnnouncementThreads,
            InvalidJSONForUploadedLottieFile = 170001,
            UploadedLottiesCannotContainRasterizedImages,
            StickerMaximumFramerateExceeded,
            StickerFrameCountExceedsMaximumOf1000Frames,
            LottieAnimationMaximumDimensionsExceeded,
            StickerFramerateIsTooSmallOrTooLarge,
            StickerAnimationDurationExceedsMaximumOf5Seconds,
            CannotUpdateAFinishedEvent = 180000,
            FailedToCreateStageNeededForStageEvent = 180002,
            MessageWasBlockedByAutomaticModeration = 200000,
            TitleWasBlockedByAutomaticModeration,
            WebhooksPostedToForumChannelsMustHaveAThreadNameOrThreadId = 220001,
            WebhooksPostedToForumChannelsCannotHaveBothAThreadNameAndThreadId,
            WebhooksCanOnlyCreateThreadsInForumChannels,
            WebhookServicesCannotBeUsedInForumChannels,
            MessageBlockedByHarmfulLinksFilter = 240000,
            CannotEnableOnboardingRequirementsAreNotMet = 350000,
            CannotUpdateOnboardingWhileBelowRequirements,
            FailedToBanUsers = 500000,
            PollVotingBlocked = 520000,
            PollExpired,
            InvalidChannelTypeForPollCreation,
            CannotEditAPollMessage,
            CannotUseAnEmojiIncludedWithThePoll,
            CannotExpireANonPollMessage = 520006,
    }

    /// <summary>
    /// https://discord.com/developers/docs/reference#locales
    /// </summary>
    public static class Locales
    {
        public const string Indonesian = "id";
        public const string Danish = "da";
        public const string German = "de";
        public const string EnglishUK = "en-GB";
        public const string EnglishUS = "en-US";
        public const string Spanish = "es-ES";
        public const string SpanishLATAM = "es-419";
        public const string French = "fr";
        public const string Croatian = "hr";
        public const string Italian = "it";
        public const string Lithuanian = "lt";
        public const string Hungarian = "hu";
        public const string Dutch = "nl";
        public const string Norwegian = "no";
        public const string Polish = "pl";
        public const string PortugueseBR = "pt-BR";
        public const string Romanian = "ro";
        public const string Finnish = "fi";
        public const string Swedish = "sv-SE";
        public const string Vietnamese = "vi";
        public const string Turkish = "tr";
        public const string Czech = "cs";
        public const string Greek = "el";
        public const string Bulgarian = "bg";
        public const string Russian = "ru";
        public const string Ukrainian = "uk";
        public const string Hindi = "hi";
        public const string Thai = "th";
        public const string ChineseCH = "zh-CN";
        public const string Japanese = "ja";
        public const string ChineseTW = "zh-TW";
        public const string Korean = "ko";
    }
}
